### ISSUE TITLE
ZIP Source Code

### ISSUE THREAD

**Issue by KaspianCow** [KASBOTCOIN/KASBOTMINER#1]
Malwarebytes detected a neshta infector when attempting to run the .exe
I'm no expert in diagnosing code, but only relaying what Malwarebytes detected.
I would love to get more information on this detection!

**Comment by nembo9860** [comment]
Hi, it is not a Malware or malicious software. The source code is simple and compiled with a python famous compiler. It is not digitally signed and this is the reason why many antivirus or online scanners identify it as malicious but it is not. It is completely safe. Eventually you can run it inside a Virtual Machine if you feel safer. For obvious reasons we cannot distribute the source code until the Kasbot Rewards period will be over
